### ISSUE TITLE
A few questions on FLAML

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#168]
Hi Team FLAML:

Thank you for your great work and timely support. So far FLAML works well in our internal modeling workflow and creates significant values by increasing the efficiency of HPO and automl, especially with gigantic datasets.

My team has a few extra questions on FLAML. They do not impact the implementation of FLAML for us but we do want to know the answers. We are mostly a R team so probably some of these questions are trivial for experts in python.

1. When building customized xgboost learners, we can either import XGBClassifier from xgboost.sklearn or XGBoostSklearnEstimator from flaml.model and use it as the parent class for the customized learner. Is there any difference between these two approaches? Similar for LGBMClassifier from either lightgbm directly or flaml.model.

2. After finishing the automl, we usually print the best model returned for each learner in a report. For some learners (such as xgboost), the details of the model can be printed out directly:

>>> print(automl.best_model_for_estimator('MonotonicXgboost'))
 XGBClassifier(base_score=0.5, booster='gbtree',
               colsample_bylevel=0.8093192534175951, colsample_bynode=1,
               colsample_bytree=1, eval_metric='auc',
               gamma=5.483342083437219e-05, gpu_id=-1, importance_type='gain',
               interaction_constraints='', learning_rate=0.02013126244001672,
               max_delta_step=0, max_depth=8, min_child_weight=185, missing=nan,
               monotone_constraints=(-1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1,
                                   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
                                     -1, -1, -1, -1, -1, -1, -1, -1, ...),
             n_estimators=268, n_jobs=8, num_parallel_tree=1,
              random_state=19850606, reg_alpha=7.703791502692487e-12,
               reg_lambda=0.21435076435874728, scale_pos_weight=1, subsample=0.7,
              tree_method='exact', use_label_encoder=False,
           validate_parameters=1, verbosity=None)

However, for others such as catboost, we only get things as below:

>>> print(automl.best_model_for_estimator('MonotonicCatboost'))
<catboost.core.CatBoostClassifier object at 0x7f5bca6d41d0>

What causes the difference?

Appreciate your help.

**Comment by sonichi** [comment]
Thanks for the feedback. Please see my answers below.

1. The estimator class in flaml.model does a few extra things for each training. For example, the XGBoostSklearnEstimator will preprocess the categorical columns because XGBClassifier doesn't handle raw categorical features. And when a time budget is given, the number of estimators may be modified to satisfy the budget. The `size` function is also built-in. If you don't need these functions, you don't need to import the estimator class from flaml.model.
2. The output depends on the `str()` method for each class. You can either implement your own `str()` function for your custom estimator class, or print `.params` which is the configuration used.

**Comment by flippercy** [comment]
Thank you!
