### ISSUE TITLE
In 'Catboost' estimator, entire parameters are not able to obtained.

### ISSUE THREAD

**Issue by kabrate** [microsoft/FLAML#169]
When estimator is 'catboost', automo.model only print <flaml.model.CatBoostEstimator object at 0x000001768BFC5AC8>. Entire parameters are not able to obtained. Besides, i check variables in the debugger, automl1.best_config only has two paremeters.

![image](https://user-images.githubusercontent.com/26816327/129977783-6d02fcaf-ce93-48de-8c3b-8a65aee76f29.png)

![image](https://user-images.githubusercontent.com/26816327/129978060-1a9d5caf-ba32-4b54-95ae-3eafc9aa7227.png)

**Comment by qingyun-wu** [comment]
Hi @kabrate,

This is because currently flaml is only tuning two hyperparameters (you can find the current search space for catboost [here](https://github.com/microsoft/FLAML/blob/main/flaml/model.py#L643)) of the catboost model instead of all the hyperparameters. All the other hyperparameters except these two are all using default values.

Do you just want to get the values for the entire hyperparameters or also want to tune them? In the former case, you can use the `get_all_params()` API of CatboostClassifier or CatboostRegressor to get all the parameters. More specifically, in your case, use `automl1.model.model.get_all_params()`. In the latter case, you will need to add a custom catboost estimator with your preferred search space.

Please refer to this issue (https://github.com/microsoft/FLAML/issues/144) for the discussion about extending the search space for catboost model if you are interested in tuning more hyperparameters of catboost. You are also welcome to join the discussions, ask questions and share your use cases on [gitter](https://gitter.im/FLAMLer/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). 


Thank you!
