### ISSUE TITLE
 why the condition is 'resoure * self.resource_multiple_factor > self.max_resource' in _round method?

### ISSUE THREAD

**Issue by Oath4Love** [microsoft/FLAML#212]
In flow2.py file, I confuse that why the condition is 'resoure * self.resource_multiple_factor > self.max_resource'
```python
 def _round(self, resource) -> float:
        ''' round the resource to self.max_resource if close to it
        '''
        if resource * self.resource_multiple_factor > self.max_resource:
            return self.max_resource
        return resource
```

**Comment by qingyun-wu** [comment]
Hi @Oath4Love, thank you for your question. This is a heuristic to ensure we do not have a rung of resource that is too close (which intuitively unnecessary) to max_resource. For example, say the max_resource is 450, min_resource is 100, and the multiple factor is 2, with this heuristic, we will have resource rung 100, 200, 450 instead of 100, 200, 400, 450.
