### ISSUE TITLE
Errors when ensemble = True

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#29]
Hi:

There is an error message when fitting models using customized monotonic learners with ensemble = True:

RuntimeError: Cannot clone object <__main__.MyMonotonicLightGBMGBDTClassifier object at 0x7f9ef2999310>, as the constructor either does not set or modifies parameter monotone_constraints

I assume it is due to the monotone_constraints added to self.params. Any suggestion on how to fix it?

Usually we won't implement an ensemble of boosting models but would be great if we can figure out a solution!

Thank you.

**Comment by sonichi** [comment]
When `ensemble=True` and `monotone_constraints` is in self.params, you need to set the `monotone_constraints` according to **params in the constructor if it is passed. For example: https://github.com/microsoft/FLAML/blob/d18d292081dbf34ffb2b1e3948acaf37569ebedd/flaml/model.py#L373

It's required by scikit-learn.

**Comment by flippercy** [comment]
Got it. Thank you!

**Comment by sonichi** [comment]
It fits an ensemble for the best base model of each learner. You should be able to see some msg like:

[flaml.automl: 02-17 11:42:05] {1161} INFO - ensemble: StackingClassifier(estimators=[('lgbm',
                                <flaml.model.LGBMEstimator object at 0x0000027F30E05F88>),
                               ('RGF',
                                <test.test_automl.MyRegularizedGreedyForest object at 0x0000027F30E00C88>)],
                   final_estimator=<flaml.model.LGBMEstimator object at 0x0000027F30E05F88>,
                   n_jobs=1, passthrough=True)

It ensembles one lgbm and one RGF model in this example. 

The increased ensemble time may be due to larger and better models found later in the search. You can check the config of the best individual models to verify that.

**Comment by lucazav** [comment]
@sonichi Is there a way to get the composition of the ensemble (learners used and their weight)?
